// File: comb_alu_front.v
// Generated by MyHDL 0.7
// Date: Fri Dec 21 17:05:53 2012

module comb_alu_front (
	aluop,
	func,
	shamt,
	op1,
	op2,
	out_1,
	out_2
);

input [4:0] aluop;
input [5:0] func;
input [4:0] shamt;
input signed [31:0] op1;
input signed [31:0] op2;
output signed [31:0] out_1;
reg signed [31:0] out_1;
output signed [31:0] out_2;
reg signed [31:0] out_2;

reg [1:0] shift_ctl;
reg signed [31:0] shift_in;
reg signed [31:0] shift_out;
reg [4:0] shift_amount;

`include "alu_code.v"

parameter SLL = 2'b01;
parameter SRL = 2'b10;
parameter SRA = 2'b11;

always @(aluop, shamt, op1, op2, shift_out, func) begin: COMB_ALU_FRONT_LOGIC
	case (aluop)
		ALU_OP_RFORMAT: begin
			case (func)
				'h0: begin
					shift_in = op2;
					shift_ctl = SLL;
					shift_amount = shamt;
					out_2 = 0;
					out_1 = shift_out;
				end
				'h4: begin
					shift_in = op2;
					shift_ctl = SLL;
					shift_amount = op1[5-1:0];
					out_2 = 0;
					out_1 = shift_out;
				end
				'h2: begin
					shift_in = op2;
					shift_ctl = SRL;
					shift_amount = shamt;
					out_2 = 0;
					out_1 = shift_out;
				end
				'h3: begin
					shift_in = op2;
					shift_ctl = SRA;
					shift_amount = shamt;
					out_2 = 0;
					out_1 = shift_out;
				end
				'h7: begin
					shift_in = op2;
					shift_ctl = SRA;
					shift_amount = op1[5-1:0];
					out_2 = 0;
					out_1 = shift_out;
				end
				default: begin
					out_1 = op1;
					out_2 = op2;
				end
			endcase
		end
		ALU_OP_ORI: begin
			out_1 = op1;
			out_2 = {16'h0, op2[16-1:0]};
		end
		ALU_OP_ANDI: begin
			out_1 = op1;
			out_2 = {16'h0, op2[16-1:0]};
		end
		ALU_OP_LUI: begin
			out_1 = 0;
			out_2 = $signed({op2[16-1:0], 16'h0});
		end
		ALU_OP_BGEZ: begin
			out_1 = op1;
			out_2 = 0;
		end
		ALU_OP_BGEZAL: begin
			out_1 = op1;
			out_2 = 0;
		end
		ALU_OP_BLTZ: begin
			out_1 = op1;
			out_2 = 0;
		end
		ALU_OP_BLTZAL: begin
			out_1 = op1;
			out_2 = 0;
		end
		ALU_OP_BGTZ: begin
			out_1 = op1;
			out_2 = 0;
		end
		ALU_OP_BLEZ: begin
			out_1 = op1;
			out_2 = 0;
		end
		default: begin
			out_1 = op1;
			out_2 = op2;
		end
	endcase
end


always @(shift_ctl, shift_amount, shift_in) begin: COMB_ALU_FRONT_SHIFT__LOGIC
	case (shift_ctl)
		2'b00: begin
			shift_out = 0;
		end
		SLL: begin
			case (shift_amount)
				'h0: begin
					shift_out = shift_in;
				end
				'h1: begin
					shift_out = $signed({shift_in[31-1:0], 1'h0});
				end
				'h2: begin
					shift_out = $signed({shift_in[30-1:0], 2'h0});
				end
				'h3: begin
					shift_out = $signed({shift_in[29-1:0], 3'h0});
				end
				'h4: begin
					shift_out = $signed({shift_in[28-1:0], 4'h0});
				end
				'h5: begin
					shift_out = $signed({shift_in[27-1:0], 5'h0});
				end
				'h6: begin
					shift_out = $signed({shift_in[26-1:0], 6'h0});
				end
				'h7: begin
					shift_out = $signed({shift_in[25-1:0], 7'h0});
				end
				'h8: begin
					shift_out = $signed({shift_in[24-1:0], 8'h0});
				end
				'h9: begin
					shift_out = $signed({shift_in[23-1:0], 9'h0});
				end
				'ha: begin
					shift_out = $signed({shift_in[22-1:0], 10'h0});
				end
				'hb: begin
					shift_out = $signed({shift_in[21-1:0], 11'h0});
				end
				'hc: begin
					shift_out = $signed({shift_in[20-1:0], 12'h0});
				end
				'hd: begin
					shift_out = $signed({shift_in[19-1:0], 13'h0});
				end
				'he: begin
					shift_out = $signed({shift_in[18-1:0], 14'h0});
				end
				'hf: begin
					shift_out = $signed({shift_in[17-1:0], 15'h0});
				end
				'h10: begin
					shift_out = $signed({shift_in[16-1:0], 16'h0});
				end
				'h11: begin
					shift_out = $signed({shift_in[15-1:0], 17'h0});
				end
				'h12: begin
					shift_out = $signed({shift_in[14-1:0], 18'h0});
				end
				'h13: begin
					shift_out = $signed({shift_in[13-1:0], 19'h0});
				end
				'h14: begin
					shift_out = $signed({shift_in[12-1:0], 20'h0});
				end
				'h15: begin
					shift_out = $signed({shift_in[11-1:0], 21'h0});
				end
				'h16: begin
					shift_out = $signed({shift_in[10-1:0], 22'h0});
				end
				'h17: begin
					shift_out = $signed({shift_in[9-1:0], 23'h0});
				end
				'h18: begin
					shift_out = $signed({shift_in[8-1:0], 24'h0});
				end
				'h19: begin
					shift_out = $signed({shift_in[7-1:0], 25'h0});
				end
				'h1a: begin
					shift_out = $signed({shift_in[6-1:0], 26'h0});
				end
				'h1b: begin
					shift_out = $signed({shift_in[5-1:0], 27'h0});
				end
				'h1c: begin
					shift_out = $signed({shift_in[4-1:0], 28'h0});
				end
				'h1d: begin
					shift_out = $signed({shift_in[3-1:0], 29'h0});
				end
				'h1e: begin
					shift_out = $signed({shift_in[2-1:0], 30'h0});
				end
				'h1f: begin
					shift_out = $signed({shift_in[1-1:0], 31'h0});
				end
			endcase
		end
		SRL: begin
			case (shift_amount)
				'h0: begin
					shift_out = shift_in;
				end
				'h1: begin
					shift_out = $signed({1'h0, shift_in[32-1:1]});
				end
				'h2: begin
					shift_out = $signed({2'h0, shift_in[32-1:2]});
				end
				'h3: begin
					shift_out = $signed({3'h0, shift_in[32-1:3]});
				end
				'h4: begin
					shift_out = $signed({4'h0, shift_in[32-1:4]});
				end
				'h5: begin
					shift_out = $signed({5'h0, shift_in[32-1:5]});
				end
				'h6: begin
					shift_out = $signed({6'h0, shift_in[32-1:6]});
				end
				'h7: begin
					shift_out = $signed({7'h0, shift_in[32-1:7]});
				end
				'h8: begin
					shift_out = $signed({8'h0, shift_in[32-1:8]});
				end
				'h9: begin
					shift_out = $signed({9'h0, shift_in[32-1:9]});
				end
				'ha: begin
					shift_out = $signed({10'h0, shift_in[32-1:10]});
				end
				'hb: begin
					shift_out = $signed({11'h0, shift_in[32-1:11]});
				end
				'hc: begin
					shift_out = $signed({12'h0, shift_in[32-1:12]});
				end
				'hd: begin
					shift_out = $signed({13'h0, shift_in[32-1:13]});
				end
				'he: begin
					shift_out = $signed({14'h0, shift_in[32-1:14]});
				end
				'hf: begin
					shift_out = $signed({15'h0, shift_in[32-1:15]});
				end
				'h10: begin
					shift_out = $signed({16'h0, shift_in[32-1:16]});
				end
				'h11: begin
					shift_out = $signed({17'h0, shift_in[32-1:17]});
				end
				'h12: begin
					shift_out = $signed({18'h0, shift_in[32-1:18]});
				end
				'h13: begin
					shift_out = $signed({19'h0, shift_in[32-1:19]});
				end
				'h14: begin
					shift_out = $signed({20'h0, shift_in[32-1:20]});
				end
				'h15: begin
					shift_out = $signed({21'h0, shift_in[32-1:21]});
				end
				'h16: begin
					shift_out = $signed({22'h0, shift_in[32-1:22]});
				end
				'h17: begin
					shift_out = $signed({23'h0, shift_in[32-1:23]});
				end
				'h18: begin
					shift_out = $signed({24'h0, shift_in[32-1:24]});
				end
				'h19: begin
					shift_out = $signed({25'h0, shift_in[32-1:25]});
				end
				'h1a: begin
					shift_out = $signed({26'h0, shift_in[32-1:26]});
				end
				'h1b: begin
					shift_out = $signed({27'h0, shift_in[32-1:27]});
				end
				'h1c: begin
					shift_out = $signed({28'h0, shift_in[32-1:28]});
				end
				'h1d: begin
					shift_out = $signed({29'h0, shift_in[32-1:29]});
				end
				'h1e: begin
					shift_out = $signed({30'h0, shift_in[32-1:30]});
				end
				'h1f: begin
					shift_out = $signed({31'h0, shift_in[32-1:31]});
				end
			endcase
		end
		SRA: begin
			case (shift_in[31])
				'h0: begin
					case (shift_amount)
						'h0: begin
							shift_out = shift_in;
						end
						'h1: begin
							shift_out = $signed({1'h0, shift_in[32-1:1]});
						end
						'h2: begin
							shift_out = $signed({2'h0, shift_in[32-1:2]});
						end
						'h3: begin
							shift_out = $signed({3'h0, shift_in[32-1:3]});
						end
						'h4: begin
							shift_out = $signed({4'h0, shift_in[32-1:4]});
						end
						'h5: begin
							shift_out = $signed({5'h0, shift_in[32-1:5]});
						end
						'h6: begin
							shift_out = $signed({6'h0, shift_in[32-1:6]});
						end
						'h7: begin
							shift_out = $signed({7'h0, shift_in[32-1:7]});
						end
						'h8: begin
							shift_out = $signed({8'h0, shift_in[32-1:8]});
						end
						'h9: begin
							shift_out = $signed({9'h0, shift_in[32-1:9]});
						end
						'ha: begin
							shift_out = $signed({10'h0, shift_in[32-1:10]});
						end
						'hb: begin
							shift_out = $signed({11'h0, shift_in[32-1:11]});
						end
						'hc: begin
							shift_out = $signed({12'h0, shift_in[32-1:12]});
						end
						'hd: begin
							shift_out = $signed({13'h0, shift_in[32-1:13]});
						end
						'he: begin
							shift_out = $signed({14'h0, shift_in[32-1:14]});
						end
						'hf: begin
							shift_out = $signed({15'h0, shift_in[32-1:15]});
						end
						'h10: begin
							shift_out = $signed({16'h0, shift_in[32-1:16]});
						end
						'h11: begin
							shift_out = $signed({17'h0, shift_in[32-1:17]});
						end
						'h12: begin
							shift_out = $signed({18'h0, shift_in[32-1:18]});
						end
						'h13: begin
							shift_out = $signed({19'h0, shift_in[32-1:19]});
						end
						'h14: begin
							shift_out = $signed({20'h0, shift_in[32-1:20]});
						end
						'h15: begin
							shift_out = $signed({21'h0, shift_in[32-1:21]});
						end
						'h16: begin
							shift_out = $signed({22'h0, shift_in[32-1:22]});
						end
						'h17: begin
							shift_out = $signed({23'h0, shift_in[32-1:23]});
						end
						'h18: begin
							shift_out = $signed({24'h0, shift_in[32-1:24]});
						end
						'h19: begin
							shift_out = $signed({25'h0, shift_in[32-1:25]});
						end
						'h1a: begin
							shift_out = $signed({26'h0, shift_in[32-1:26]});
						end
						'h1b: begin
							shift_out = $signed({27'h0, shift_in[32-1:27]});
						end
						'h1c: begin
							shift_out = $signed({28'h0, shift_in[32-1:28]});
						end
						'h1d: begin
							shift_out = $signed({29'h0, shift_in[32-1:29]});
						end
						'h1e: begin
							shift_out = $signed({30'h0, shift_in[32-1:30]});
						end
						'h1f: begin
							shift_out = $signed({31'h0, shift_in[32-1:31]});
						end
					endcase
				end
				'h1: begin
					case (shift_amount)
						'h0: begin
							shift_out = shift_in;
						end
						'h1: begin
							shift_out = $signed({1'h1, shift_in[32-1:1]});
						end
						'h2: begin
							shift_out = $signed({2'h3, shift_in[32-1:2]});
						end
						'h3: begin
							shift_out = $signed({3'h7, shift_in[32-1:3]});
						end
						'h4: begin
							shift_out = $signed({4'hf, shift_in[32-1:4]});
						end
						'h5: begin
							shift_out = $signed({5'h1f, shift_in[32-1:5]});
						end
						'h6: begin
							shift_out = $signed({6'h3f, shift_in[32-1:6]});
						end
						'h7: begin
							shift_out = $signed({7'h7f, shift_in[32-1:7]});
						end
						'h8: begin
							shift_out = $signed({8'hff, shift_in[32-1:8]});
						end
						'h9: begin
							shift_out = $signed({9'h1ff, shift_in[32-1:9]});
						end
						'ha: begin
							shift_out = $signed({10'h3ff, shift_in[32-1:10]});
						end
						'hb: begin
							shift_out = $signed({11'h7ff, shift_in[32-1:11]});
						end
						'hc: begin
							shift_out = $signed({12'hfff, shift_in[32-1:12]});
						end
						'hd: begin
							shift_out = $signed({13'h1fff, shift_in[32-1:13]});
						end
						'he: begin
							shift_out = $signed({14'h3fff, shift_in[32-1:14]});
						end
						'hf: begin
							shift_out = $signed({15'h7fff, shift_in[32-1:15]});
						end
						'h10: begin
							shift_out = $signed({16'hffff, shift_in[32-1:16]});
						end
						'h11: begin
							shift_out = $signed({17'h1ffff, shift_in[32-1:17]});
						end
						'h12: begin
							shift_out = $signed({18'h3ffff, shift_in[32-1:18]});
						end
						'h13: begin
							shift_out = $signed({19'h7ffff, shift_in[32-1:19]});
						end
						'h14: begin
							shift_out = $signed({20'hfffff, shift_in[32-1:20]});
						end
						'h15: begin
							shift_out = $signed({21'h1fffff, shift_in[32-1:21]});
						end
						'h16: begin
							shift_out = $signed({22'h3fffff, shift_in[32-1:22]});
						end
						'h17: begin
							shift_out = $signed({23'h7fffff, shift_in[32-1:23]});
						end
						'h18: begin
							shift_out = $signed({24'hffffff, shift_in[32-1:24]});
						end
						'h19: begin
							shift_out = $signed({25'h1ffffff, shift_in[32-1:25]});
						end
						'h1a: begin
							shift_out = $signed({26'h3ffffff, shift_in[32-1:26]});
						end
						'h1b: begin
							shift_out = $signed({27'h7ffffff, shift_in[32-1:27]});
						end
						'h1c: begin
							shift_out = $signed({28'hfffffff, shift_in[32-1:28]});
						end
						'h1d: begin
							shift_out = $signed({29'h1fffffff, shift_in[32-1:29]});
						end
						'h1e: begin
							shift_out = $signed({30'h3fffffff, shift_in[32-1:30]});
						end
						'h1f: begin
							shift_out = $signed({31'h7fffffff, shift_in[32-1:31]});
						end
					endcase
				end
			endcase		
		end
	endcase
end

endmodule
