// File: latch_if_id.v
// Generated by MyHDL 0.7
// Date: Sat Dec 22 14:23:52 2012


`timescale 1ns/10ps

module latch_if_id (
    clk,
    rst,
    instruction_in,
    ip_in,
    instruction_out,
    ip_out,
    stall
);
// Latch to control state between Instruction Fetch and Instruction Decoder
// 
// clk -- trigger
// rst -- reset
// instruction_in  -- 32 bits signal input
// pc_adder_in -- 32 bits signal input
// instruction_out  -- 32 bits signal output for instruction decoder
// pc_adder_out -- 32 bits signal output for pc_add
// 
// stall -- inhibit the count increment

input [0:0] clk;
input [0:0] rst;
input [31:0] instruction_in;
input [31:0] ip_in;
output [31:0] instruction_out;
reg [31:0] instruction_out;
output [31:0] ip_out;
reg [31:0] ip_out;
input [0:0] stall;






always @(posedge clk) begin: LATCH_IF_ID_LATCH
    if ((rst == 1)) begin
        instruction_out <= 0;
        ip_out <= 0;
    end
    else begin
        if ((!stall)) begin
            instruction_out <= instruction_in;
            ip_out <= ip_in;
        end
    end
end

endmodule
