// File: program_counter.v
// Generated by MyHDL 0.7
// Date: Sat Dec 22 14:27:41 2012


`timescale 1ns/10ps

module program_counter (
    clk,
    ip_in,
    ip_out, 
    stall
);
// clk : clock signal
// input: the input count
// output: address output

input [0:0] clk;
input [4:0] ip_in;
input [0:0] stall;
output [4:0] ip_out;
reg [4:0] ip_out;

always @(negedge clk) begin: PROGRAM_COUNTER_UPDATE
    if ((!stall)) begin
        ip_out <= ip_in; 
    end
end

endmodule
